import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="h-screen flex flex-col">
          <div className='bg-gray-900 px-8 flex items-center justify-between py-4 shadow-sm text-white'> Denamycal LR </div>
          <main className='flex-1 p-2'> {children} </main>
        </div>
      </body>
    </html>
  )
}
